version: "3"

services:
  postgres:
    image: postgres:11.3
    container_name: postgres_container
    restart: unless-stopped
    tty: true
    ports:
      - 127.0.0.1:7432:5432
    environment:
      - PGHOST=localhost
      - PGDATABASE=postgres
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /var/keycloak/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
    ports:
       - 127.0.0.1:8081:8080
    volumes:
    - ./keycloak:/var/keycloak
    depends_on:
      - postgres
  app:
    build: .
    network_mode: host
    image: test-task
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:7432/postgres"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
#      KEYCLOAK_AUTH_SERVER_URL: "http://keycloak:8080/auth"
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - postgres
      - keycloak
