spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: ' postgres'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate.format_sql: true
server:
  error:
    include-message: always
    include-stacktrace: never
